[project]
name = "coursework-1"
version = "0.1.0"
description = ""
authors = [{name = "natalakozlova",email = "natamedoed22@gmail.com"}]
requires-python = ">=3.14"
dependencies = [
    "flake8 (>=7.3.0,<8.0.0)",
    "black (>=26.3.1,<27.0.0)",
    "isort (>=8.0.1,<9.0.0)",
    "mypy (>=1.20.0,<2.0.0)",

]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
tests = [
    "pytest (>=9.0.2,<10.0.0)"
]
